### ISSUE TITLE
boto to boto3

### ISSUE THREAD

**Issue by rmad17** [ryan-roemer/django-cloud-browser#12]
I saw that boto is used for both AWS and Google Cloud Storage. Shouldn't boto be upgraded to boto3? Not sure if boto3 supports google cloud storage though.

**Comment by c-w** [comment]
Note that once https://github.com/ryan-roemer/django-cloud-browser/pull/20 is merged, AWS S3 and Google Cloud Storage could be accessed via libcloud ([see docs](https://libcloud.readthedocs.io/en/latest/storage/drivers/openstack_swift.html)) so this would alleviate the need for the library upgrade.

**Comment by c-w** [comment]
Resolving since there is now the workaround via libcloud.
