### ISSUE TITLE
Refactor Rackspace to OpenStack

### ISSUE THREAD

**Issue by ryan-roemer** [ryan-roemer/django-cloud-browser#16]
Change Rackspace's `python-cloudfiles` (which doesn't work on Python3 and is deprecated) to OpenStack's `python-swiftclient`.

**Comment by c-w** [comment]
Note that once https://github.com/ryan-roemer/django-cloud-browser/pull/20 is merged, OpenStack Swift storage could be accessed via libcloud ([see docs](https://libcloud.readthedocs.io/en/latest/storage/drivers/openstack_swift.html)) so this would alleviate the need for the refactor.

**Comment by c-w** [comment]
Resolving since there is now the workaround via libcloud.
