### ISSUE TITLE
AWS Account name

### ISSUE THREAD

**Issue by jwill490** [ryan-roemer/django-cloud-browser#33]
Hi all,

Thanks for the plugin.

I'm trying to configure this with an AWS s3 bucket and I'm a little confused about the settings terminology.

What should go with 'CLOUD_BROWSER_AWS_ACCOUNT'? Does that refer to the account name/email? Or the AWS account ID?

**Comment by c-w** [comment]
I'd recommend to use the [libcloud](https://libcloud.apache.org/) backend which supports AWS S3. The required configuration values are:

```python
CLOUD_BROWSER_DATASTORE = "ApacheLibcloud"
CLOUD_BROWSER_APACHE_LIBCLOUD_PROVIDER = "S3"
CLOUD_BROWSER_APACHE_LIBCLOUD_ACCOUNT = "<insert s3 api key here>"
CLOUD_BROWSER_APACHE_LIBCLOUD_SECRET_KEY = "<insert s3 secret key here>"
```

**Comment by c-w** [comment]
Resolving. Please feel free to reopen if you still have questions or comments. Thanks!
