### ISSUE TITLE
S3 objects with white spaces are not supported

### ISSUE THREAD

**Issue by yigal-rozenberg** [ryan-roemer/django-cloud-browser#40]
When clicking on a S3 object (file) that includes white spaces there is a 404 error.
Looks like the URLs need to be decoded and escaped characters need to be replaced in the document view code.

**Comment by c-w** [comment]
Thanks for reporting this. The behavior was fixed for paths in https://github.com/ryan-roemer/django-cloud-browser/pull/38 and now for document names in https://github.com/ryan-roemer/django-cloud-browser/pull/41.

**Comment by c-w** [comment]
@yigal-rozenberg A fix for this has been published in version 0.5.4 ([PyPI](https://pypi.org/project/django-cloud-browser/0.5.4/), [DockerHub](https://hub.docker.com/layers/cwolff/django-cloud-browser/0.5.4/images/sha256-cc0d449515cf64332c28e5c1e280bb20d7086d7cce0d73b63be38ab8758929d0)).
