### ISSUE TITLE
Mutation Ops: Add a "read-only" display mode.

### ISSUE THREAD

**Issue by ryan-roemer** [ryan-roemer/django-cloud-browser#8]
With instructions for _enforcing_ on underlying data store (AWS, fs, etc.)

**Comment by c-w** [comment]
@ryan-roemer Could you provide more context on this issue? Is this still relevant?

**Comment by ryan-roemer** [comment]
I think this is a vestige of https://github.com/ryan-roemer/django-cloud-browser/blob/master/TODO.rst#api when I was envisioning mutation operations available for the browser (and then wanting some clear means -- either by careful code and/or support for something like a separate read-only AWS account or something) to prevent any mutations from happening.

... if there's no mutation in our likely future then probably best to close this issue!
